### Etapa 1: Entendimento do Dataset

##### Task: Carregar dataset e realizar a inspeção inicial

In [1]:
import pandas as pd
import numpy as np

In [2]:
churn_clientes = pd.read_csv("../data/raw/dataset_churn_clientes.csv")
churn_clientes

,ID_Cliente,Idade,Genero,Estado,Plano,Tempo_Cliente_Meses,Mensalidade,Uso_Mensal_Horas,Quantidade_Chamados,Atrasos_Pagamento,Forma_Pagamento,Churn
0,1,58,Masculino,PE,Básico,4,73.0,9,3,1,Cartão de Crédito,Não
1,2,23,Feminino,PR,Básico,30,66.0,62,8,1,Débito Automático,Não
2,3,69,Feminino,RJ,Básico,21,72.0,16,4,1,Pix,Não
3,4,24,Feminino,RJ,Padrão,45,106.0,75,11,3,Débito Automático,Não
4,5,71,Feminino,RJ,Premium,47,250.0,114,1,0,Boleto,Não
...,...,...,...,...,...,...,...,...,...,...,...,...
2005,1274,30,Feminino,MG,Básico,67,51.0,15,1,0,Cartão de Crédito,Não
2006,939,68,Feminino,RS,NaN,61,93.0,86,0,6,Boleto,Não
2007,1732,31,Masculino,PE,Premium,47,227.0,72,12,6,Cartão de Crédito,Sim
2008,66,24,Masculino,RS,Básico,38,57.0,10,4,0,Cartão de Crédito,Não
2009,1324,47,Feminino,MG,Premium,35,209.0,51,12,1,Cartão de Crédito,Não

In [3]:
churn_clientes.dtypes

ID_Cliente               int64
Idade                    int64
Genero                     str
Estado                     str
Plano                      str
Tempo_Cliente_Meses      int64
Mensalidade            float64
Uso_Mensal_Horas         int64
Quantidade_Chamados      int64
Atrasos_Pagamento        int64
Forma_Pagamento            str
Churn                      str
dtype: object

In [4]:
churn_clientes.describe()

,ID_Cliente,Idade,Tempo_Cliente_Meses,Mensalidade,Uso_Mensal_Horas,Quantidade_Chamados,Atrasos_Pagamento
count,2010.000000,2010.000000,2010.000000,1995.000000,2010.000000,2010.000000,2010.000000
mean,1001.034826,45.277114,36.427861,126.875188,62.124876,6.126866,2.954229
std,577.330122,16.900474,20.757723,60.995075,33.477180,3.826153,2.013121
min,1.000000,18.000000,1.000000,50.000000,5.000000,0.000000,0.000000
25%,501.250000,30.000000,18.000000,72.000000,32.000000,3.000000,1.000000
50%,1001.500000,45.000000,37.000000,112.000000,62.000000,6.000000,3.000000
75%,1499.750000,60.000000,54.000000,181.000000,91.750000,10.000000,5.000000
max,2000.000000,75.000000,72.000000,250.000000,120.000000,12.000000,6.000000

##### Task: Analisar estatisticas descritivas

In [5]:
media_idade = churn_clientes["Idade"].mean()
print(f"Media de idade dos clientes: {media_idade}")

Media de idade dos clientes: 45.277114427860695

In [6]:
media_mensalidade = churn_clientes["Mensalidade"].mean()
print(f"Media das mensalidades: {media_mensalidade}")

Media das mensalidades: 126.87518796992481

In [7]:
media_tempo_cliente = churn_clientes["Tempo_Cliente_Meses"].mean()
print(f"Media de meses que os clientes ficam na empresa: {media_tempo_cliente}")

Media de meses que os clientes ficam na empresa: 36.42786069651741

In [8]:
planos_distribuicao = churn_clientes.groupby("Plano").size().reset_index(name="quantidade_clientes")
planos_distribuicao

     Plano  quantidade_clientes
0   Básico                  696
1   Padrão                  659
2  Premium                  639

In [9]:
taxa_inicio = len(churn_clientes)
taxa_sairam = (churn_clientes["Churn"] == "Sim").sum()
taxa_churn = taxa_sairam / taxa_inicio * 100
print(f"taxa inicial de churn: {taxa_churn}")

taxa inicial de churn: 29.45273631840796

### Etapa 2: Limpeza e Tratamento dos Dados

##### Task: Identificar e tratar valores ausentes

In [10]:
churn_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 2010 entries, 0 to 2009
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Cliente           2010 non-null   int64
 1   Idade                2010 non-null   int64
 2   Genero               1995 non-null   str
 3   Estado               1995 non-null   str
 4   Plano                1994 non-null   str
 5   Tempo_Cliente_Meses  2010 non-null   int64
 6   Mensalidade          1995 non-null   float64
 7   Uso_Mensal_Horas     2010 non-null   int64
 8   Quantidade_Chamados  2010 non-null   int64
 9   Atrasos_Pagamento    2010 non-null   int64
 10  Forma_Pagamento      1995 non-null   str
 11  Churn                2010 non-null   str
dtypes: float64(1), int64(6), str(5)
memory usage: 254.2 KB

- Campos com valores nulos: Genero, Estado, Plano, Mensalidade, Forma_Pagamento

In [11]:
churn_clientes["Genero"] = churn_clientes["Genero"].fillna("Indefinido")
churn_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 2010 entries, 0 to 2009
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Cliente           2010 non-null   int64
 1   Idade                2010 non-null   int64
 2   Genero               2010 non-null   str
 3   Estado               1995 non-null   str
 4   Plano                1994 non-null   str
 5   Tempo_Cliente_Meses  2010 non-null   int64
 6   Mensalidade          1995 non-null   float64
 7   Uso_Mensal_Horas     2010 non-null   int64
 8   Quantidade_Chamados  2010 non-null   int64
 9   Atrasos_Pagamento    2010 non-null   int64
 10  Forma_Pagamento      1995 non-null   str
 11  Churn                2010 non-null   str
dtypes: float64(1), int64(6), str(5)
memory usage: 254.1 KB

In [12]:
churn_clientes["Estado"] = churn_clientes["Estado"].fillna("ND") # ND = Nao Definido
churn_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 2010 entries, 0 to 2009
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Cliente           2010 non-null   int64
 1   Idade                2010 non-null   int64
 2   Genero               2010 non-null   str
 3   Estado               2010 non-null   str
 4   Plano                1994 non-null   str
 5   Tempo_Cliente_Meses  2010 non-null   int64
 6   Mensalidade          1995 non-null   float64
 7   Uso_Mensal_Horas     2010 non-null   int64
 8   Quantidade_Chamados  2010 non-null   int64
 9   Atrasos_Pagamento    2010 non-null   int64
 10  Forma_Pagamento      1995 non-null   str
 11  Churn                2010 non-null   str
dtypes: float64(1), int64(6), str(5)
memory usage: 253.8 KB

In [13]:
plano_intervalo = churn_clientes.groupby("Plano")["Mensalidade"].agg(["min", "max"]).reset_index()
plano_intervalo

     Plano    min    max
0   Básico   50.0   80.0
1   Padrão   90.0  140.0
2  Premium  160.0  250.0

In [14]:
mascara = churn_clientes["Plano"].isna()

condicoes = [
    churn_clientes.loc[mascara, "Mensalidade"].between(50, 80),
    churn_clientes.loc[mascara, "Mensalidade"].between(90, 140),
    churn_clientes.loc[mascara, "Mensalidade"].between(160, 250)
]

valores = ["Básico", "Padrão", "Premium"]

churn_clientes.loc[mascara, "Plano"] = np.select(condicoes, valores, default=None)
churn_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 2010 entries, 0 to 2009
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Cliente           2010 non-null   int64
 1   Idade                2010 non-null   int64
 2   Genero               2010 non-null   str
 3   Estado               2010 non-null   str
 4   Plano                2010 non-null   str
 5   Tempo_Cliente_Meses  2010 non-null   int64
 6   Mensalidade          1995 non-null   float64
 7   Uso_Mensal_Horas     2010 non-null   int64
 8   Quantidade_Chamados  2010 non-null   int64
 9   Atrasos_Pagamento    2010 non-null   int64
 10  Forma_Pagamento      1995 non-null   str
 11  Churn                2010 non-null   str
dtypes: float64(1), int64(6), str(5)
memory usage: 253.7 KB

In [17]:
planos_valores = {
    "Básico": 65,
    "Padrão": 115,
    "Premium": 205
}

mascara = churn_clientes["Mensalidade"].isna()

churn_clientes.loc[mascara, "Mensalidade"] = (
    churn_clientes.loc[mascara, "Plano"].map(planos_valores)
)
churn_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 2010 entries, 0 to 2009
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Cliente           2010 non-null   int64
 1   Idade                2010 non-null   int64
 2   Genero               2010 non-null   str
 3   Estado               2010 non-null   str
 4   Plano                2010 non-null   str
 5   Tempo_Cliente_Meses  2010 non-null   int64
 6   Mensalidade          2010 non-null   float64
 7   Uso_Mensal_Horas     2010 non-null   int64
 8   Quantidade_Chamados  2010 non-null   int64
 9   Atrasos_Pagamento    2010 non-null   int64
 10  Forma_Pagamento      1995 non-null   str
 11  Churn                2010 non-null   str
dtypes: float64(1), int64(6), str(5)
memory usage: 253.7 KB

In [18]:
churn_clientes["Forma_Pagamento"] = churn_clientes["Forma_Pagamento"].fillna("Débito Automático")
churn_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 2010 entries, 0 to 2009
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Cliente           2010 non-null   int64
 1   Idade                2010 non-null   int64
 2   Genero               2010 non-null   str
 3   Estado               2010 non-null   str
 4   Plano                2010 non-null   str
 5   Tempo_Cliente_Meses  2010 non-null   int64
 6   Mensalidade          2010 non-null   float64
 7   Uso_Mensal_Horas     2010 non-null   int64
 8   Quantidade_Chamados  2010 non-null   int64
 9   Atrasos_Pagamento    2010 non-null   int64
 10  Forma_Pagamento      2010 non-null   str
 11  Churn                2010 non-null   str
dtypes: float64(1), int64(6), str(5)
memory usage: 253.7 KB

- Tratamento de valores ausentes concluido